package General;

public enum ETOKEN {
	PLUS, MINUS, MULT, DIV, EQ, LPAREN, RPAREN, COMMA, AND, OR, LBRACK, RBRACK, 
	SEMI, NEQ, LESSEREQ, LESS, GREATEREQ, GREATER, ASSIGN, COLON, INTLIT, ID,
	STRLIT, RETURN, ARRAY, BREAK, DO, ELSE, END, FOR, FUNC, 
	IF, IN, LET, NIL, OF, THEN, TO, TYPE, VAR, WHILE, ENDIF, BEGIN, ENDDO;
}
